name: Release Movment.hpp

on:
  push:
    tags:
      - 'v*'  # Se ejecuta cuando se hace push de un tag que comience con "v", por ejemplo, v1.0.0

permissions:
  contents: write  # Otorga permisos necesarios para crear releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Validate Movment.hpp exists
        run: |
          if [ ! -f "Mov/Movment.hpp" ]; then
            echo "Error: Mov/Movment.hpp no existe"
            exit 1
          fi

      - name: Create zip with Movment.hpp, docs and meta
        run: |
          set -e
          rm -rf release
          mkdir -p release
          # Copia el archivo principal
          cp Mov/Movment.hpp release/
          # Copia la carpeta "docs" si existe
          if [ -d "docs" ]; then
            cp -r docs release/
          else
            echo "La carpeta docs no existe. Se omite su copia."
          fi
          # Copia el archivo "meta" si existe (ajusta la ruta si es necesario)
          if [ -f "meta" ]; then
            cp meta release/
          else
            echo "El archivo meta no existe. Se omite su copia."
          fi
          cd release
          # Crea el ZIP; si docs o meta no existen, zip los omitirá
          zip -r Movment.zip Movment.hpp docs meta

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: release/Movment.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: rm -rf release