name: Release Movment.hpp

on:
  push:
    tags:
      - 'v*'  # Se ejecuta cuando se hace push de un tag que comience con "v", por ejemplo, v1.0.0

permissions:
  contents: write  # Otorga permisos necesarios para crear releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Validate Movment.hpp exists
        run: |
          if [ ! -f "Mov/Movment.hpp" ]; then
            echo "Error: Mov/Movment.hpp no existe"
            exit 1
          fi

      - name: Create zip with Movment.hpp
        run: |
          set -e
          rm -rf release
          mkdir -p release
          cp Mov/Movment.hpp release/
          cd release
          zip Movment.zip Movment.hpp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: release/Movment.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: rm -rf release